# Generated by Django 4.0 on 2022-12-31 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_memberrole_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=50)),
                ('item_price', models.IntegerField(blank=True)),
                ('item_quantity_received', models.IntegerField()),
                ('item_quantity_available', models.IntegerField(blank=True)),
                ('item_purchased_date', models.DateField(auto_now_add=True)),
                ('item_units', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity_lent', models.IntegerField(blank=True)),
                ('item_lent_date', models.DateField(auto_now_add=True)),
                ('item_is_lent', models.BooleanField(default=True)),
                ('date_returned_date', models.DateField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Broken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity_broken', models.IntegerField(blank=True)),
                ('item_broken_date', models.DateField(auto_now_add=True)),
                ('item_is_broken', models.BooleanField(default=True)),
                ('date_repaired', models.DateField(auto_now=True)),
                ('item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.item')),
            ],
        ),
    ]
