# Generated by Django 4.0 on 2023-01-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_complete_completed_alter_memberrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrole',
            name='role',
            field=models.IntegerField(blank=True, choices=[(3, 'Secretary'), (2, 'Member'), (4, 'Storekeeper'), (1, 'Admin')]),
        ),
    ]
