# Generated by Django 4.0 on 2023-01-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_memberrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='about',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='memberrole',
            name='role',
            field=models.IntegerField(blank=True, choices=[(4, 'Storekeeper'), (3, 'Secretary'), (2, 'Member'), (1, 'Admin')]),
        ),
    ]
