# Generated by Django 3.2.16 on 2023-01-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_memberrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrole',
            name='role',
            field=models.IntegerField(blank=True, choices=[(3, 'Secretary'), (2, 'Member'), (4, 'Storekeeper'), (1, 'Admin')]),
        ),
    ]
