# Generated by Django 3.2.16 on 2023-01-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_memberrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrole',
            name='role',
            field=models.IntegerField(blank=True, choices=[(4, 'Storekeeper'), (2, 'Member'), (1, 'Admin'), (3, 'Secretary')]),
        ),
    ]
