# Generated by Django 3.2.16 on 2023-04-17 08:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_photo_description'),
        ('core', '0012_alter_memberrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='patrol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.patrol'),
        ),
        migrations.AlterField(
            model_name='memberrole',
            name='profile',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.profile'),
        ),
        migrations.AlterField(
            model_name='memberrole',
            name='role',
            field=models.IntegerField(blank=True, choices=[(4, 'Storekeeper'), (3, 'Secretary'), (1, 'Admin'), (2, 'Member')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^.*$', 'Invalid username')]),
        ),
    ]
