# Generated by Django 3.2.16 on 2023-04-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20230417_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberrole',
            name='role',
            field=models.IntegerField(blank=True, choices=[(2, 'Member'), (3, 'Secretary'), (4, 'Storekeeper'), (1, 'Admin')]),
        ),
    ]
