# Generated by Django 3.2.16 on 2023-01-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='nights',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
