# Generated by Django 3.2.16 on 2023-04-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_hike_nights'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='coordinator',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
