# Generated by Django 4.0 on 2023-01-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patrol', '0002_alter_attendance_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
